<?php
/** @var string $term */
/** @var array $users */

//dd($users);

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<!--=======================================================-->
<!--<table>-->
<!--    <thead>-->
<!--    <tr>-->
<!--        <th>id</th>-->
<!--        <th>firstName</th>-->
<!--    </tr>-->
<!--    </thead>-->
<!--    <tbody>-->
<!--    --><?php //foreach ($users as $user) : ?>
<!--    <tr>-->
<!--        <td><p>--><?php //= $user['id'] ?><!--</p></td>-->
<!--        <td><a href="/users/--><?php //= $user['id'] ?><!--">--><?php //= $user['firstName'] ?><!--</a></td>-->
<!--    </tr>-->
<!--    --><?php //endforeach; ?>
<!--    </tbody>-->
<!--</table>-->


<!--                 lesson 13                             -->
<!--=======================================================-->

<!--<form action="/users" method="get">-->
<!--    <label>-->
<!--        <input type="search" name="term" value="--><?php //= htmlspecialchars($term ?? '') ?><!--">-->
<!--    </label>-->
<!--    <input type="submit" value="Search" />-->
<!--</form>-->
<!---->
<!--<hr>-->
<!---->
<!--<ul>-->
<!--    --><?php //foreach ($users as $user) : ?>
<!--    <li>--><?php //= htmlspecialchars($user) ?><!--</li>-->
<!--    --><?php //endforeach; ?>
<!--</ul>-->

<!--=======================================================-->

<!---->
<!--<form action="/users" method="get">-->
<!--    <label>-->
<!--        <input type="search" name="term" value="--><?php //= htmlspecialchars($term ?? '') ?><!--">-->
<!--    </label>-->
<!--    <input type="submit" value="Search" />-->
<!--</form>-->
<!---->
<!--<hr>-->
<!---->
<!--<ul>-->
<!--    --><?php //foreach ($users as $user) : ?>
<!--    <li>--><?php //= htmlspecialchars($user['firstName']) ?><!--</li>-->
<!--    --><?php //endforeach; ?>
<!--</ul>-->
<!---->
<!--</body>-->
<!--</html>-->

<!--
<!--=======================================================-->
<a href="/users/new">Create New User</a>
<h1>All Users</h1>

<table>
    <thead>
    <tr>
        <th>id</th>
        <th>nickname</th>
        <th>email</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($users as $user) : ?>
    <tr>
        <td><?= $user['id'] ?></td>
        <td><?= $user['name'] ?></td>
        <td><?= $user['email'] ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

