<?php



?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>New user</h1>

<form action="/users" method="post">
    <div>
        <label>Nickname:</label>
        <label>
            <input type="text" name="user[name]" value="">
        </label>
    </div>

    <div>
        <label>email:</label>
        <input type="email" name="user[email]" value="">
    </div>
    <button type="submit">Submit</button>

</form>

</body>
</html>